### ISSUE TITLE
(Organization) Combine tags like so

### ISSUE THREAD

**Issue by CharlesDLandau** [MarianiVentura/prj-rev-bwfs-dasmoto#3]
I think your code would be more readable if you point to multiple tags for repetitive key-value pairs like so:

```
h1, 
h2, 
h3, 
p {
  font-family: "Helvetica", sans-serif;
}
```

**Comment by MarianiVentura** [comment]
Charles,

Thank you.  One other thing, the way I did the pricing, I noticed that they were separate from the other text, which is not on spec.  I presume this was because I chose to use a div and class for the pricing.  Is that correct?  How would I change the pricing so it did not separate from the other text?
Michael

**Comment by CharlesDLandau** [comment]
I think using the SPAN tag inline can fix this.
